In [4]:
# data libraries
import numpy as np 
import pandas as pd 

# visualization libraries
import matplotlib.pyplot as plt 
import seaborn as sns
#import plotly.express as px


# custom eda utils
from utils.eda_utils import get_data_dict, give_time_discrepancies, give_time_interval 

In [5]:
static_information = pd.read_csv("../data/static-information.csv", delimiter=';')
data_description = pd.read_csv("../data/data_description.csv", delimiter=';')

names_list = static_information['Wind_turbine_name'].to_list()
data_dict = get_data_dict(names_list)

t0 = data_dict[0]
t1 = data_dict[1]
t2 = data_dict[2]
t3 = data_dict[3]

var_index = ['Date_time_nr',  'Wind_turbine_name']
var_turb = ['Ba_avg', 'P_avg', 'Q_avg', 'Ya_avg', 'Yt_avg', 'Va_avg', 'Rs_avg', 'Rbt_avg', 'Rm_avg']
var_turb_sens=['Ws1_avg', 'Ws2_avg', 'Ws_avg', 'Wa_avg', 'Ot_avg']
var_ext = ['temp', 'pressure', 'humidity','wind_speed', 'wind_deg', 'rain_1h', 'snow_1h']

# Timestamps discrepatncies  in unix timestaps


In [9]:
give_time_interval(t0)
give_time_interval(t1)
give_time_interval(t2)
give_time_interval(t3)

'start:'

np.int64(1515798000)

'end:+'

np.int64(1356994800)

'entries:'

(261138,)

'start:'

np.int64(1515798000)

'end:+'

np.int64(1356994800)

'entries:'

(261471,)

'start:'

np.int64(1515798000)

'end:+'

np.int64(1356994800)

'entries:'

(261812,)

'start:'

np.int64(1515798000)

'end:+'

np.int64(1356994800)

'entries:'

(261414,)

In [8]:
display(give_time_discrepancies(t0))
display(give_time_discrepancies(t1))
display(give_time_discrepancies(t2))
display(give_time_discrepancies(t3))

array([    nan,    600.,   1200.,  87000.,   4200.,   7800.,  28200.,
         2400.,  34800.,   6600.,   1800.,  19800.,  37200.,  42000.,
        17400.,  11400., 123600.,   3000.,  25200.,   6000.,  24600.,
        83400.,   4800.,  22800.,  27000.,  13800.,   8400.,   3600.,
         9600.,  16200.,  21600.,  42600.,  59400.,  97800.,  10800.,
        20400.,   5400.,  10200.,  12000.,   7200.,  54600.,  34200.,
        49800.,  12600.,   9000.,  15600.,  37800.,  18000.,  36000.,
       109200.,  43800.,  44400.])

array([    nan,    600.,   1200.,  87000.,   4200.,   7800.,  27600.,
        14400.,  34800.,  10800.,  15000.,   4800.,  35400.,   9000.,
       478800.,   6600.,   1800.,   3600.,   2400.,  17400.,  13200.,
         7200., 124200.,   8400.,  22200.,   6000.,  26400.,   5400.,
        20400.,  27000.,   3000.,  24600.,  21000.,  30600.,  58800.,
        12000.,  23400.,  10200.,  12600.,  37800.,  53400.])

array([    nan,    600.,   1200.,  87000.,   4200.,   9000.,   1800.,
        28200.,   2400.,  34800.,   7800.,   3000.,   4800.,  19800.,
        36000.,  14400.,  39000.,  16800.,   6600., 124200.,  18000.,
         6000.,   5400.,  22800.,  26400.,   3600.,  11400.,   9600.,
        45000.,  16200.,   8400.,  18600.,  48600.,  13200.,  54000.,
        43200.,  36600.,  54600.,  10200.,  27000.,  53400.,   7200.,
        15600.])

array([    nan,    600.,   1200.,  87000.,   4200.,   5400.,  28200.,
         2400.,  34800.,  37800.,   7800., 161400.,   7200.,  21000.,
        35400.,   1800.,   6000.,  39000.,  18600.,   4800., 124200.,
        20400.,   3600.,  23400.,  24600.,  21600.,  33000.,  12600.,
        89400.,  18000.,   6600.,   9600.,  16200.,   3000.,   9000.,
        10200.,   8400.,  52200.,  11400.,  17400.,  12000.,  27000.,
        27600.,  10800.,  14400.,  13800.,  26400.])

In [ ]:

t0['Date_time_nr'].plot()


In [2]:
import matplotlib.pyplot as plt

In [10]:
t0.head(1)

Date_time  Date_time_nr Wind_turbine_name  Ba_avg  \
0  2013-01-01T00:00:00+01:00    1356994800            R80736    -1.0   

       P_avg      Q_avg  Ya_avg     Yt_avg  Ws1_avg  Ws2_avg  ...     Rs_avg  \
0  801.22998  67.559998   286.0  20.129999     7.52     7.76  ...  16.950001   

     Rbt_avg     Rm_avg  temp  pressure  humidity  wind_speed  wind_deg  \
0  26.049999  4298.0498  5.39    1011.0      75.0        5.66     180.0   

   rain_1h  snow_1h  
0      0.0      0.0  

[1 rows x 24 columns]

In [ ]:
t0.info()

In [ ]:
def preprocess(data):
    # useless cols
    data = data.drop(columns=['Date_time', 'Wind_turbine_name'])
    #set datetime unix format as timestap
    data = data.set_index('Date_time_nr')

    # create index array    
    end = 1515798000
    start = 1356994800
    period = 600 
    periods_timedelta =  (end - start)/period
    index_array = np.arange(int(periods_timedelta)+1) * period + start
    
    for idx in index_array:
        if idx not in data.index:
        # start with all NaNs
            data.loc[idx] = {col: pd.NA for col in data.columns}
        
    # ensure sorted index if needed
    data.sort_index(inplace=True)

    data.ffill(inplace=True)

    return data 

In [ ]:
data0_p = preprocess(t0)

In [ ]:
t0.isna().sum()
data0_p.isna().sum()
mask = data0_p.isna()
data0_p[mask].head()
data0_p.index.is_monotonic_increasing

In [84]:
data0_p.head(1)

Ba_avg      P_avg      Q_avg  Ya_avg     Yt_avg  Ws1_avg  \
Date_time_nr                                                             
1356994800      -1.0  801.22998  67.559998   286.0  20.129999     7.52   

              Ws2_avg  Ws_avg  Wa_avg  Va_avg  ...     Rs_avg    Rbt_avg  \
Date_time_nr                                   ...                         
1356994800       7.76    7.64  286.19    0.16  ...  16.950001  26.049999   

                 Rm_avg  temp  pressure  humidity  wind_speed  wind_deg  \
Date_time_nr                                                              
1356994800    4298.0498  5.39    1011.0      75.0        5.66     180.0   

              rain_1h  snow_1h  
Date_time_nr                    
1356994800        0.0      0.0  

[1 rows x 21 columns]

In [86]:
data0_p.ffill(inplace=True)

In [87]:
data0_p.isna().sum()

Ba_avg        0
P_avg         0
Q_avg         0
Ya_avg        0
Yt_avg        0
Ws1_avg       0
Ws2_avg       0
Ws_avg        0
Wa_avg        0
Va_avg        0
Ot_avg        0
Rs_avg        0
Rbt_avg       0
Rm_avg        0
temp          0
pressure      0
humidity      0
wind_speed    0
wind_deg      0
rain_1h       0
snow_1h       0
dtype: int64

In [88]:
data0_p.info()

<class 'pandas.core.frame.DataFrame'>
Index: 264673 entries, 1356994800 to 1515798000
Data columns (total 21 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Ba_avg      264673 non-null  float64
 1   P_avg       264673 non-null  float64
 2   Q_avg       264673 non-null  float64
 3   Ya_avg      264673 non-null  float64
 4   Yt_avg      264673 non-null  float64
 5   Ws1_avg     264673 non-null  float64
 6   Ws2_avg     264673 non-null  float64
 7   Ws_avg      264673 non-null  float64
 8   Wa_avg      264673 non-null  float64
 9   Va_avg      264673 non-null  float64
 10  Ot_avg      264673 non-null  float64
 11  Rs_avg      264673 non-null  float64
 12  Rbt_avg     264673 non-null  float64
 13  Rm_avg      264673 non-null  float64
 14  temp        264673 non-null  float64
 15  pressure    264673 non-null  float64
 16  humidity    264673 non-null  float64
 17  wind_speed  264673 non-null  float64
 18  wind_deg    264673 non-null  float64